# Unit03 Numpy | 數值計算基礎

本 Notebook 介紹 NumPy 模組的完整功能與應用，涵蓋陣列操作、數學運算、統計分析、線性代數等核心概念。

## 目標
- 理解 NumPy 陣列的基本概念與特性
- 掌握陣列建立、索引、切片與變形技巧
- 運用向量化運算提升程式效能
- 應用 NumPy 數學函式與統計分析
- 實作化工數據處理與模擬範例
- 掌握線性代數運算與廣播機制

---
## 0. 載入相關套件

In [147]:
# 基礎套件
import numpy as np
import matplotlib.pyplot as plt
import time
import warnings
warnings.filterwarnings('ignore')

# 檢查 NumPy 版本
print(f"NumPy 版本: {np.__version__}")

# 設定隨機種子以確保結果可重現
SEED = 42
np.random.seed(SEED)

# 設定 matplotlib 中文顯示
plt.rcParams['axes.unicode_minus'] = False

print("✓ 套件載入完成！")

NumPy 版本: 1.23.5
✓ 套件載入完成！


---
# Hello World!

In [34]:
# print hello world
print("Hello World!")

Hello World!


## print 用法教學

In [75]:
# print 變數用法教學
var_example = 123
print(f"變數 var_example 的值為: {var_example}")

變數 var_example 的值為: 123


In [96]:
# print 換行方式
print("這是第一行。\n這是第二行。")


這是第一行。
這是第二行。


In [99]:
# print 空一行
print("這是第一行。")
print()
print("這是第二行。")

這是第一行。

這是第二行。


---
## 1. NumPy 基本概念

### 1.1 什麼是 NumPy 陣列？

NumPy 陣列 (ndarray) 是一個多維度的同質資料容器，與 Python 原生的 list 相比：
- **資料型態**：所有元素必須相同型態
- **效能**：高效能（C 語言實作）
- **記憶體**：連續記憶體配置
- **運算**：支援向量化運算
- **功能**：豐富的數學函式

### 1.2 為什麼使用向量化運算？

使用向量化運算可以大幅提升效能並簡化程式碼。以下示範溫度轉換：

In [2]:
# Python list 方式（慢）
celsius_list = [0, 10, 20, 30, 40, 50]
fahrenheit_list = []
for temp in celsius_list:
    fahrenheit_list.append(temp * 9/5 + 32)
print("Python list 方式:", fahrenheit_list)

Python list 方式: [32.0, 50.0, 68.0, 86.0, 104.0, 122.0]


In [3]:
# NumPy 向量化運算（快）
celsius_array = np.array([0, 10, 20, 30, 40, 50])
fahrenheit_array = celsius_array * 9/5 + 32
print("NumPy 向量化方式:", fahrenheit_array)

NumPy 向量化方式: [ 32.  50.  68.  86. 104. 122.]


---
## 2. 建立 NumPy 陣列

### 2.1 從 Python List 建立

In [5]:
# 一維陣列
arr_1d = np.array([1, 2, 3, 4, 5])
print("一維陣列:", arr_1d)

一維陣列: [1 2 3 4 5]


In [6]:
# ndim 屬性
print(f"維度 (ndim): {arr_1d.ndim}")

維度 (ndim): 1


In [7]:
# shape 屬性
print(f"形狀 (shape): {arr_1d.shape}")

形狀 (shape): (5,)


In [8]:
# size 屬性
print(f"大小 (size): {arr_1d.size}")

大小 (size): 5


In [9]:
# dtype 屬性
print(f"資料型態 (dtype): {arr_1d.dtype}")

資料型態 (dtype): int32


In [10]:
# 二維陣列
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("\n二維陣列:")
print(arr_2d)


二維陣列:
[[1 2 3]
 [4 5 6]]


In [11]:
# ndim 屬性
print(f"維度: {arr_2d.ndim}")


維度: 2


In [12]:
# shape 屬性
print(f"形狀: {arr_2d.shape}")

形狀: (2, 3)


In [13]:
# 三維陣列
arr_3d = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("\n三維陣列:")
print(arr_3d)
print(f"形狀: {arr_3d.shape}")  # (2, 2, 2)


三維陣列:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
形狀: (2, 2, 2)


### 2.2 使用內建函式建立陣列

**全零陣列、全一陣列與指定值陣列**

In [14]:
# 建立全零陣列
zeros = np.zeros((3, 4))
print("全零陣列 (3x4):")
print(zeros)

全零陣列 (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
# 建立全一陣列
ones = np.ones((2, 3))
print("\n全一陣列 (2x3):")
print(ones)


全一陣列 (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# 建立指定值的陣列
full_array = np.full((3, 3), 7.5)
print("\n全 7.5 陣列 (3x3):")
print(full_array)


全 7.5 陣列 (3x3):
[[7.5 7.5 7.5]
 [7.5 7.5 7.5]
 [7.5 7.5 7.5]]


**等差數列與均勻分佈**

In [17]:
# np.arange：類似 Python 的 range
# arange(start, stop, step)
arr_range = np.arange(0, 10, 2)
print("arange(0, 10, 2):", arr_range)  # [0 2 4 6 8]

arange(0, 10, 2): [0 2 4 6 8]


In [18]:
# np.linspace：在指定範圍內產生均勻分佈的數值
# linspace(start, stop, num)
arr_linspace = np.linspace(0, 1, 5)
print("\nlinspace(0, 1, 5):", arr_linspace)  # [0.   0.25 0.5  0.75 1.  ]



linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


In [19]:
# 化工應用：建立溫度範圍
temperature = np.linspace(25, 100, 11)  # 25°C 到 100°C，11個點
print("\n溫度範圍 (25-100°C, 11點):")
print(temperature)


溫度範圍 (25-100°C, 11點):
[ 25.   32.5  40.   47.5  55.   62.5  70.   77.5  85.   92.5 100. ]


**單位矩陣與對角矩陣**

In [20]:
# 單位矩陣（對角線為 1，其餘為 0）
identity = np.eye(4)
print("單位矩陣 (4x4):")
print(identity)

單位矩陣 (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# 對角矩陣
diagonal = np.diag([1, 2, 3, 4])
print("\n對角矩陣:")
print(diagonal)


對角矩陣:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### 2.3 隨機數生成

In [22]:
# 均勻分佈 [0, 1)
uniform = np.random.rand(3, 3)
print("均勻分佈隨機數 (3x3):")
print(uniform)

均勻分佈隨機數 (3x3):
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [23]:
# 標準常態分佈（平均 0，標準差 1）
normal = np.random.randn(1000)
print(f"\n常態分佈 (1000 個樣本):")
print(f"平均值: {normal.mean():.4f}")
print(f"標準差: {normal.std():.4f}")


常態分佈 (1000 個樣本):
平均值: 0.0239
標準差: 0.9999


In [24]:
# 指定範圍的隨機整數
integers = np.random.randint(0, 100, size=(3, 4))
print("\n隨機整數 [0, 100) (3x4):")
print(integers)


隨機整數 [0, 100) (3x4):
[[11 86 11 12]
 [24 44 18 54]
 [99 44  7 92]]


In [25]:
# 化工應用：模擬測量誤差
true_value = 50.0  # 真實值
measurement_noise = np.random.normal(0, 0.5, 100)  # 平均 0，標準差 0.5
measurements = true_value + measurement_noise
print(f"\n測量數據模擬:")
print(f"真實值: {true_value:.2f}")
print(f"測量平均值: {measurements.mean():.4f}")
print(f"測量標準差: {measurements.std():.4f}")


測量數據模擬:
真實值: 50.00
測量平均值: 50.0267
測量標準差: 0.5008


---
## 3. 陣列索引與切片

### 3.1 一維陣列索引

In [26]:
arr = np.array([10, 20, 30, 40, 50])
print("原始陣列:", arr)

原始陣列: [10 20 30 40 50]


In [27]:
# 正向索引
print(f"\narr[0] = {arr[0]}")    # 10（第一個元素）
print(f"arr[2] = {arr[2]}")      # 30（第三個元素）


arr[0] = 10
arr[2] = 30


In [28]:
# 反向索引
print(f"arr[-1] = {arr[-1]}")    # 50（最後一個元素）
print(f"arr[-2] = {arr[-2]}")    # 40（倒數第二個元素）

arr[-1] = 50
arr[-2] = 40


In [29]:
# 切片 [start:stop:step]
print(f"\narr[1:4] = {arr[1:4]}")      # [20 30 40]


arr[1:4] = [20 30 40]


In [30]:
print(f"arr[:3] = {arr[:3]}")          # [10 20 30]（前三個）

arr[:3] = [10 20 30]


In [31]:
print(f"arr[2:] = {arr[2:]}")          # [30 40 50]（從第三個到最後）

arr[2:] = [30 40 50]


In [32]:
print(f"arr[::2] = {arr[::2]}")        # [10 30 50]（每隔一個）

arr[::2] = [10 30 50]


In [33]:
print(f"arr[::-1] = {arr[::-1]}")      # [50 40 30 20 10]（反轉）

arr[::-1] = [50 40 30 20 10]


### 3.2 二維陣列索引

In [35]:
# 建立二維陣列
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("原始二維陣列:")
print(arr_2d)

原始二維陣列:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
# 索引單一元素 [row, column]
print(f"\narr_2d[0, 0] = {arr_2d[0, 0]}")    # 1


arr_2d[0, 0] = 1


In [37]:
print(f"arr_2d[1, 2] = {arr_2d[1, 2]}")      # 7

arr_2d[1, 2] = 7


In [38]:
print(f"arr_2d[-1, -1] = {arr_2d[-1, -1]}")  # 12

arr_2d[-1, -1] = 12


In [39]:
# 索引整列或整欄
print(f"\n第二列 arr_2d[1, :] = {arr_2d[1, :]}")    # [5 6 7 8]


第二列 arr_2d[1, :] = [5 6 7 8]


In [40]:
print(f"第三欄 arr_2d[:, 2] = {arr_2d[:, 2]}")      # [3 7 11]

第三欄 arr_2d[:, 2] = [ 3  7 11]


In [41]:
# 切片範圍
print(f"\n子陣列 arr_2d[0:2, 1:3]:")
print(arr_2d[0:2, 1:3])


子陣列 arr_2d[0:2, 1:3]:
[[2 3]
 [6 7]]


### 3.3 布林索引

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("原始陣列:", arr)

原始陣列: [ 1  2  3  4  5  6  7  8  9 10]


In [43]:
# 建立布林遮罩
mask = arr > 5
print(f"\n布林遮罩 (arr > 5): {mask}")


布林遮罩 (arr > 5): [False False False False False  True  True  True  True  True]


In [44]:
# 使用遮罩篩選
print(f"篩選結果: {arr[mask]}")  # [6 7 8 9 10]

篩選結果: [ 6  7  8  9 10]


In [45]:
# 簡寫
print(f"\n簡寫 arr[arr > 5]: {arr[arr > 5]}")


簡寫 arr[arr > 5]: [ 6  7  8  9 10]


In [46]:
# 多條件組合（& 表示 AND，| 表示 OR）
print(f"\narr[(arr > 3) & (arr < 8)]: {arr[(arr > 3) & (arr < 8)]}")  # [4 5 6 7]


arr[(arr > 3) & (arr < 8)]: [4 5 6 7]


In [47]:
print(f"arr[(arr < 3) | (arr > 8)]: {arr[(arr < 3) | (arr > 8)]}")    # [1 2 9 10]

arr[(arr < 3) | (arr > 8)]: [ 1  2  9 10]


In [48]:
# 化工應用：篩選異常數據
temperature = np.array([25.1, 25.3, 98.5, 25.0, 24.9, 25.2])
print(f"\n溫度數據: {temperature}")


溫度數據: [25.1 25.3 98.5 25.  24.9 25.2]


In [49]:
# 篩選溫度異常（> 30°C）
abnormal_temp = temperature[temperature > 30]
print(f"異常溫度 (>30°C): {abnormal_temp}")
print(f"異常數量: {len(abnormal_temp)} / {len(temperature)}")

異常溫度 (>30°C): [98.5]
異常數量: 1 / 6


### 3.4 花式索引

In [50]:
arr = np.array([10, 20, 30, 40, 50])

# 使用整數陣列索引
indices = np.array([0, 2, 4])
print(f"arr[indices]: {arr[indices]}")  # [10 30 50]

arr[indices]: [10 30 50]


In [51]:
# 二維陣列的花式索引
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

rows = np.array([0, 2])
cols = np.array([1, 2])
print(f"\narr_2d[rows, cols]: {arr_2d[rows, cols]}")  # [2 9]


arr_2d[rows, cols]: [2 9]


---
## 4. 陣列運算

### 4.1 基本算術運算

In [52]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print("arr1 =", arr1)
print("arr2 =", arr2)

arr1 = [1 2 3 4]
arr2 = [5 6 7 8]


In [53]:
# 基本運算
print(f"\narr1 + arr2 = {arr1 + arr2}")  # [ 6  8 10 12]


arr1 + arr2 = [ 6  8 10 12]


In [54]:
print(f"arr1 - arr2 = {arr1 - arr2}")    # [-4 -4 -4 -4]

arr1 - arr2 = [-4 -4 -4 -4]


In [55]:
print(f"arr1 * arr2 = {arr1 * arr2}")    # [ 5 12 21 32]

arr1 * arr2 = [ 5 12 21 32]


In [56]:
print(f"arr1 / arr2 = {arr1 / arr2}")    # [0.2   0.333 0.428 0.5]

arr1 / arr2 = [0.2        0.33333333 0.42857143 0.5       ]


In [57]:
print(f"arr1 ** 2 = {arr1 ** 2}")        # [ 1  4  9 16]

arr1 ** 2 = [ 1  4  9 16]


In [58]:
# 與純量運算
print(f"\narr1 + 10 = {arr1 + 10}")      # [11 12 13 14]
print(f"arr1 * 2 = {arr1 * 2}")          # [2 4 6 8]


arr1 + 10 = [11 12 13 14]
arr1 * 2 = [2 4 6 8]


In [59]:
# 化工應用：濃度轉換
concentration_ppm = np.array([100, 200, 300, 400])  # ppm
concentration_percent = concentration_ppm / 10000   # 轉換為 %
print(f"\n濃度轉換:")
print(f"ppm: {concentration_ppm}")
print(f"%: {concentration_percent}")


濃度轉換:
ppm: [100 200 300 400]
%: [0.01 0.02 0.03 0.04]


### 4.2 比較運算

In [60]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

print("arr1 =", arr1)
print("arr2 =", arr2)
print(f"\narr1 > 3: {arr1 > 3}")         # [False False False  True  True]
print(f"arr1 == arr2: {arr1 == arr2}")   # [False False  True False False]
print(f"arr1 < arr2: {arr1 < arr2}")     # [ True  True False False False]

arr1 = [1 2 3 4 5]
arr2 = [5 4 3 2 1]

arr1 > 3: [False False False  True  True]
arr1 == arr2: [False False  True False False]
arr1 < arr2: [ True  True False False False]


In [61]:
# 化工應用：檢查製程參數是否在規格範圍內
pressure = np.array([100, 105, 98, 110, 102])
spec_lower = 95
spec_upper = 108

within_spec = (pressure >= spec_lower) & (pressure <= spec_upper)
print(f"\n壓力數據: {pressure}")
print(f"規格範圍: [{spec_lower}, {spec_upper}]")
print(f"符合規格: {within_spec}")
print(f"符合規格數量: {within_spec.sum()} / {len(pressure)}")


壓力數據: [100 105  98 110 102]
規格範圍: [95, 108]
符合規格: [ True  True  True False  True]
符合規格數量: 4 / 5


### 4.3 通用函式 (Universal Functions, ufunc)

In [62]:
arr = np.array([1, 4, 9, 16, 25])
print("原始陣列:", arr)

原始陣列: [ 1  4  9 16 25]


In [63]:
# 平方根
print(f"\n平方根: {np.sqrt(arr)}")  # [1. 2. 3. 4. 5.]


平方根: [1. 2. 3. 4. 5.]


In [64]:
# 指數與對數
print(f"指數 exp([1,2,3]): {np.exp([1, 2, 3])}")

指數 exp([1,2,3]): [ 2.71828183  7.3890561  20.08553692]


In [65]:
print(f"自然對數 log(arr): {np.log(arr)}")

自然對數 log(arr): [0.         1.38629436 2.19722458 2.77258872 3.21887582]


In [66]:
print(f"常用對數 log10(arr): {np.log10(arr)}")

常用對數 log10(arr): [0.         0.60205999 0.95424251 1.20411998 1.39794001]


In [67]:
# 三角函式
angles = np.array([0, np.pi/4, np.pi/2, np.pi]) 
print(f"\n角度 (radians): {angles}")
print(f"sin(angles): {np.sin(angles)}")
print(f"cos(angles): {np.cos(angles)}")


角度 (rad): [0.         0.78539816 1.57079633 3.14159265]
sin(angles): [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
cos(angles): [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]


In [68]:
# 化工應用：Arrhenius 方程式計算反應速率常數
# k = A * exp(-Ea / (R * T))
A = 1e10              # 頻率因子
Ea = 50000            # 活化能 (J/mol)
R = 8.314             # 氣體常數 (J/mol·K)
T = np.array([300, 350, 400, 450, 500])  # 溫度 (K)

k = A * np.exp(-Ea / (R * T))
print(f"\nArrhenius 方程式計算:")
print(f"溫度 (K): {T}")
print(f"反應速率常數 k:")
for i, temp in enumerate(T):
    print(f"  T={temp}K: k={k[i]:.4e}")


Arrhenius 方程式計算:
溫度 (K): [300 350 400 450 500]
反應速率常數 k:
  T=300K: k=1.9675e+01
  T=350K: k=3.4486e+02
  T=400K: k=2.9542e+03
  T=450K: k=1.5702e+04
  T=500K: k=5.9751e+04


---
## 5. 陣列變形與組合

### 5.1 改變陣列形狀

In [69]:
# 原始陣列
arr = np.arange(12)
print("原始陣列:", arr)

原始陣列: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [70]:
# reshape：改變形狀（不改變數據）
arr_2d = arr.reshape(3, 4)
print("\nreshape(3, 4):")
print(arr_2d)


reshape(3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [71]:
arr_3d = arr.reshape(2, 3, 2)
print(f"\nreshape(2, 3, 2) 形狀: {arr_3d.shape}")


reshape(2, 3, 2) 形狀: (2, 3, 2)


In [72]:
# 自動計算維度（使用 -1）
arr_auto = arr.reshape(4, -1)  # 自動計算為 (4, 3)
print(f"reshape(4, -1) 形狀: {arr_auto.shape}")

reshape(4, -1) 形狀: (4, 3)


In [73]:
# flatten：攤平為一維陣列
arr_flat = arr_2d.flatten()
print(f"\nflatten(): {arr_flat}")


flatten(): [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [74]:
# ravel：類似 flatten，但可能回傳 view（不複製）
arr_ravel = arr_2d.ravel()
print(f"ravel(): {arr_ravel}")

ravel(): [ 0  1  2  3  4  5  6  7  8  9 10 11]


### 5.2 轉置與軸交換

In [76]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("原始陣列:")
print(arr)

原始陣列:
[[1 2 3]
 [4 5 6]]


In [77]:
# 轉置
arr_T = arr.T
print("\n轉置 arr.T:")
print(arr_T)


轉置 arr.T:
[[1 4]
 [2 5]
 [3 6]]


In [78]:
# transpose：指定軸的順序
arr_3d = np.arange(24).reshape(2, 3, 4)
print(f"\n三維陣列形狀: {arr_3d.shape}")  # (2, 3, 4)


三維陣列形狀: (2, 3, 4)


In [79]:
arr_transposed = np.transpose(arr_3d, (2, 0, 1))
print(f"轉置後形狀 (2,0,1): {arr_transposed.shape}")  # (4, 2, 3)

轉置後形狀 (2,0,1): (4, 2, 3)


### 5.3 陣列堆疊

In [82]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("arr1 =", arr1)
print("arr2 =", arr2)

arr1 = [1 2 3]
arr2 = [4 5 6]


In [83]:
# 垂直堆疊（沿著列方向）
v_stack = np.vstack([arr1, arr2])
print("垂直堆疊 vstack:")
print(v_stack)

垂直堆疊 vstack:
[[1 2 3]
 [4 5 6]]


In [84]:
# 水平堆疊（沿著欄方向）
h_stack = np.hstack([arr1, arr2])
print("\n水平堆疊 hstack:")
print(h_stack)


水平堆疊 hstack:
[1 2 3 4 5 6]


In [87]:
# 通用堆疊函式 concatenate
arr2d_1 = np.array([[1, 2], [3, 4]])
arr2d_2 = np.array([[5, 6], [7, 8]])
print("\narr2d_1:")
print(arr2d_1)
print()
print("arr2d_2:")
print(arr2d_2)


arr2d_1:
[[1 2]
 [3 4]]

arr2d_2:
[[5 6]
 [7 8]]


In [88]:
concat_0 = np.concatenate([arr2d_1, arr2d_2], axis=0)  # 垂直
print("\nconcatenate (axis=0):")
print(concat_0)


concatenate (axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [89]:
concat_1 = np.concatenate([arr2d_1, arr2d_2], axis=1)  # 水平
print("\nconcatenate (axis=1):")
print(concat_1)


concatenate (axis=1):
[[1 2 5 6]
 [3 4 7 8]]


### 5.4 陣列分割

In [90]:
arr = np.arange(16).reshape(4, 4)
print("原始陣列:")
print(arr)

原始陣列:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [94]:
# 水平分割
h_split = np.hsplit(arr, 2)  # 分成 2 個部分
print("\n水平分割 hsplit (2 parts):")
print("第一部分:")
print(h_split[0])
print()
print("第二部分:")
print(h_split[1])


水平分割 hsplit (2 parts):
第一部分:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

第二部分:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [100]:
# 垂直分割
v_split = np.vsplit(arr, 2)
print("\n垂直分割 vsplit (2 parts):")
print("第一部分:")
print(v_split[0])
print()
print("第二部分:")
print(h_split[1])


垂直分割 vsplit (2 parts):
第一部分:
[[0 1 2 3]
 [4 5 6 7]]

第二部分:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


---
## 6. 統計與聚合函式

### 6.1 基本統計量

In [102]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("數據:", data)

數據: [ 1  2  3  4  5  6  7  8  9 10]


In [103]:
# 總和與乘積
print(f"總和: {data.sum()}")          # 55

總和: 55


In [104]:
print(f"累積和: {data.cumsum()}")       # [ 1  3  6 10 15 21 28 36 45 55]

累積和: [ 1  3  6 10 15 21 28 36 45 55]


In [105]:
print(f"乘積: {data.prod()}")           # 3628800

乘積: 3628800


In [106]:
# 平均值
print(f"平均值: {data.mean()}")       # 5.5

平均值: 5.5


In [107]:
print(f"中位數: {np.median(data)}")     # 5.5

中位數: 5.5


In [108]:
# 變異數與標準差
print(f"變異數: {data.var()}")        # 8.25


變異數: 8.25


In [109]:
print(f"標準差: {data.std()}")          # 2.872

標準差: 2.8722813232690143


In [110]:
# 最大值、最小值與範圍
print(f"最大值: {data.max()}")        # 10

最大值: 10


In [111]:
print(f"最小值: {data.min()}")          # 1

最小值: 1


In [112]:
print(f"範圍 (ptp): {data.ptp()}")      # peak to peak = 9

範圍 (ptp): 9


In [113]:
# 最大值與最小值的索引位置
print(f"最大值索引: {data.argmax()}") # 9
print(f"最小值索引: {data.argmin()}")   # 0

最大值索引: 9
最小值索引: 0


### 6.2 多維陣列的統計

In [114]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("二維陣列:")
print(arr_2d)

二維陣列:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [115]:
# 整個陣列的統計
print(f"整體總和: {arr_2d.sum()}")        # 78

整體總和: 78


In [116]:
# 沿著特定軸的統計
# axis=0：沿著列方向（對每一欄做統計）
print(f"\n每欄總和 (axis=0): {arr_2d.sum(axis=0)}")    # [15 18 21 24]


每欄總和 (axis=0): [15 18 21 24]


In [117]:
# axis=1：沿著欄方向（對每一列做統計）
print(f"每列總和 (axis=1): {arr_2d.sum(axis=1)}")      # [10 26 42]

每列總和 (axis=1): [10 26 42]


In [118]:
# 平均值
print(f"每欄平均 (axis=0): {arr_2d.mean(axis=0)}")   # [5. 6. 7. 8.]
print(f"每列平均 (axis=1): {arr_2d.mean(axis=1)}")     # [2.5 6.5 10.5]

每欄平均 (axis=0): [5. 6. 7. 8.]
每列平均 (axis=1): [ 2.5  6.5 10.5]


In [119]:
# 化工應用：計算多變數製程數據的統計量
# 假設每列代表一個時間點，每欄代表一個製程變數
process_data = np.random.randn(100, 4)  # 100 時間點，4 個變數

variable_means = process_data.mean(axis=0)
variable_stds = process_data.std(axis=0)

print(f"\n化工應用：製程數據統計")
print(f"各變數平均值: {variable_means}")
print(f"各變數標準差: {variable_stds}")


化工應用：製程數據統計
各變數平均值: [-0.05969583 -0.02627702  0.02914308  0.00226654]
各變數標準差: [1.1150321  0.94143191 0.98278828 0.92080418]


### 6.3 百分位數與分位數

In [120]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 百分位數
print(f"25% 百分位數: {np.percentile(data, 25)}")  # 3.25
print(f"50% 百分位數: {np.percentile(data, 50)}")  # 5.5
print(f"75% 百分位數: {np.percentile(data, 75)}")  # 7.75

# 分位數（0-1 之間）
print(f"\n第一四分位數 (Q1): {np.quantile(data, 0.25)}")   # 3.25
print(f"第三四分位數 (Q3): {np.quantile(data, 0.75)}")     # 7.75

25% 百分位數: 3.25
50% 百分位數: 5.5
75% 百分位數: 7.75

第一四分位數 (Q1): 3.25
第三四分位數 (Q3): 7.75


In [121]:
# 化工應用：計算製程數據的控制界限
# 使用 3-sigma 規則
process_values = np.random.normal(100, 5, 1000)
mean = process_values.mean()
std = process_values.std()

ucl = mean + 3 * std  # Upper Control Limit
lcl = mean - 3 * std  # Lower Control Limit

print(f"\n製程控制界限計算:")
print(f"中心線 (CL): {mean:.2f}")
print(f"上控制界限 (UCL): {ucl:.2f}")
print(f"下控制界限 (LCL): {lcl:.2f}")


製程控制界限計算:
中心線 (CL): 99.85
上控制界限 (UCL): 114.63
下控制界限 (LCL): 85.06


---
## 7. 線性代數運算

### 7.1 矩陣乘法

In [122]:
# 元素層級乘法 (element-wise)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("矩陣 A:")
print(A)
print("\n矩陣 B:")
print(B)

矩陣 A:
[[1 2]
 [3 4]]

矩陣 B:
[[5 6]
 [7 8]]


In [124]:
element_wise = A * B
print("元素層級乘法 (A * B):")
print(element_wise)

元素層級乘法 (A * B):
[[ 5 12]
 [21 32]]


In [125]:
# 矩陣乘法（內積）
matrix_product = np.dot(A, B)
print("\n矩陣乘法 np.dot(A, B):")
print(matrix_product)


矩陣乘法 np.dot(A, B):
[[19 22]
 [43 50]]


In [126]:
# 使用 @ 運算子（Python 3.5+）
matrix_product_2 = A @ B
print("矩陣乘法 (A @ B):")
print(matrix_product_2)

矩陣乘法 (A @ B):
[[19 22]
 [43 50]]


### 7.2 矩陣運算

In [127]:
A = np.array([[1, 2], 
              [3, 4]])
print("矩陣 A:")
print(A)

矩陣 A:
[[1 2]
 [3 4]]


In [128]:
# 轉置
print("\n轉置 A.T:")
print(A.T)


轉置 A.T:
[[1 3]
 [2 4]]


In [129]:
# 行列式 (determinant)
det = np.linalg.det(A)
print(f"行列式: {det:.1f}")

行列式: -2.0


In [130]:
# 反矩陣 (inverse)
A_inv = np.linalg.inv(A)
print("\n反矩陣 A_inv:")
print(A_inv)


反矩陣 A_inv:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [131]:
# 驗證 A * A_inv = I
identity = A @ A_inv
print("\n驗證 A @ A_inv:")
print(np.round(identity))  # 四捨五入以消除浮點誤差


驗證 A @ A_inv:
[[1. 0.]
 [0. 1.]]


In [132]:
# 特徵值與特徵向量
eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"\n特徵值: {eigenvalues}")
print(f"特徵向量:")
print(eigenvectors)


特徵值: [-0.37228132  5.37228132]
特徵向量:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### 7.3 解線性方程組

In [133]:
# 解 Ax = b
# 範例：2x + 3y = 8
#       4x + 5y = 14

A = np.array([[2, 3],
              [4, 5]])
b = np.array([8, 14])

x = np.linalg.solve(A, b)
print(f"解: x = {x}")  # [1. 2.]

# 驗證
print(f"驗證 Ax = {A @ x}")  # [8. 14.]

解: x = [1. 2.]
驗證 Ax = [ 8. 14.]


In [134]:
# 化工應用：物料平衡計算
# 假設有兩個單元操作，建立物料平衡方程式
# 0.5*F1 + 0.3*F2 = 100  (組成A)
# 0.5*F1 + 0.7*F2 = 140  (組成B)

A_balance = np.array([[0.5, 0.3],
                      [0.5, 0.7]])
b_balance = np.array([100, 140])

flows = np.linalg.solve(A_balance, b_balance)
print(f"\n物料平衡計算:")
print(f"流量 F1: {flows[0]:.2f} kg/h")
print(f"流量 F2: {flows[1]:.2f} kg/h")


物料平衡計算:
流量 F1: 140.00 kg/h
流量 F2: 100.00 kg/h


---
## 8. 廣播 (Broadcasting)

廣播是 NumPy 的強大功能，允許不同形狀的陣列進行運算。
但這也經常造成Debug上的困難。

### 8.1 廣播規則與範例

In [135]:
# 範例 1：純量與陣列
arr = np.array([1, 2, 3, 4])
result = arr + 10  # 10 被廣播到每個元素
print("純量廣播:")
print(f"arr + 10 = {result}")

純量廣播:
arr + 10 = [11 12 13 14]


In [136]:
# 範例 2：一維陣列與二維陣列
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
arr_1d = np.array([10, 20, 30])

result = arr_2d + arr_1d  # arr_1d 被廣播到每一列
print("\n一維廣播到二維:")
print("arr_2d + arr_1d:")
print(result)


一維廣播到二維:
arr_2d + arr_1d:
[[11 22 33]
 [14 25 36]]


In [140]:
# 範例 3：使用 reshape 進行廣播
row = np.array([1, 2, 3])
col = np.array([10, 20, 30]).reshape(3, 1)
print(f"列陣列 row:\n{row}")
print(f"欄陣列 col:\n{col}")
print()

result = row + col  # 產生 3x3 矩陣
print("列與欄廣播:")
print("row + col:")
print(result)

列陣列 row:
[1 2 3]
欄陣列 col:
[[10]
 [20]
 [30]]

列與欄廣播:
row + col:
[[11 12 13]
 [21 22 23]
 [31 32 33]]


### 8.2 化工應用：標準化數據

In [141]:
# 假設有多個感測器的讀數（列：時間點，欄：感測器）
data = np.array([[100, 25, 1.2],
                 [110, 26, 1.3],
                 [105, 24, 1.1],
                 [115, 27, 1.4]])

print("原始數據:")
print(data)

# 計算每個感測器的平均值與標準差
mean = data.mean(axis=0)  # shape: (3,)
std = data.std(axis=0)    # shape: (3,)

# 標準化（利用廣播）
standardized = (data - mean) / std

print(f"\n平均值: {mean}")
print(f"標準差: {std}")
print(f"\n標準化數據:")
print(standardized)

# 驗證標準化後的平均值應接近 0，標準差應接近 1
print(f"\n標準化後平均值: {standardized.mean(axis=0)}")
print(f"標準化後標準差: {standardized.std(axis=0)}")

原始數據:
[[100.   25.    1.2]
 [110.   26.    1.3]
 [105.   24.    1.1]
 [115.   27.    1.4]]

平均值: [107.5   25.5    1.25]
標準差: [5.59016994 1.11803399 0.1118034 ]

標準化數據:
[[-1.34164079 -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [-0.4472136  -1.34164079 -1.34164079]
 [ 1.34164079  1.34164079  1.34164079]]

標準化後平均值: [0. 0. 0.]
標準化後標準差: [1. 1. 1.]


---
## 9. 實務應用案例

### 9.1 化工數據分析：反應動力學參數估算

In [146]:
# 一階反應動力學：ln(C) = ln(C0) - k*t
# 已知不同時間點的濃度數據，估算速率常數 k

ts = np.array([0, 10, 20, 30, 40, 50])  # 時間 (min)
concentration = np.array([1.0, 0.82, 0.67, 0.55, 0.45, 0.37])  # 濃度 (mol/L)

# 線性化處理
ln_C = np.log(concentration)
ln_C0 = ln_C[0]

# 使用線性回歸估算斜率（-k）
# 最小平方法: k = -Σ(t * ln(C)) / Σ(t^2)
k = -np.sum(ts * ln_C) / np.sum(ts ** 2)
half_life = np.log(2) / k

print("反應動力學參數估算")
print("=" * 50)
print(f"反應速率常數 k: {k:.6f} min⁻¹")
print(f"半生期 t₁/₂: {half_life:.2f} min")

# 計算預測值與誤差
ln_C_pred = ln_C0 - k * ts
C_pred = np.exp(ln_C_pred)
error = concentration - C_pred
mse = np.mean(error ** 2)

print(f"\n模型評估:")
print(f"均方誤差 (MSE): {mse:.6f}")

反應動力學參數估算
反應速率常數 k: 0.019924 min⁻¹
半生期 t₁/₂: 34.79 min

模型評估:
均方誤差 (MSE): 0.000001


### 9.2 溫度分布模擬

In [143]:
# 一維熱傳導：穩態溫度分布
# 假設管壁兩端溫度固定，計算內部溫度分布

# 參數設定
n_points = 11
T_left = 100   # 左端溫度 (°C)
T_right = 20   # 右端溫度 (°C)

# 線性溫度分布（簡化模型）
position = np.linspace(0, 1, n_points)
temperature = T_left + (T_right - T_left) * position

print(f"溫度分布模擬")
print("=" * 50)
print(f"位置: {position}")
print(f"溫度 (°C): {temperature}")

# 計算溫度梯度
gradient = np.gradient(temperature, position)
print(f"\n溫度梯度 (°C/m): {gradient}")

溫度分布模擬
位置: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
溫度 (°C): [100.  92.  84.  76.  68.  60.  52.  44.  36.  28.  20.]

溫度梯度 (°C/m): [-80. -80. -80. -80. -80. -80. -80. -80. -80. -80. -80.]


### 9.3 質量平衡計算 (CSTR 串聯)

In [144]:
# 連續攪拌槽反應器 (CSTR) 質量平衡
C_in = 10.0      # 進料濃度 (mol/L)
k = 0.5          # 反應速率常數 (1/min)
tau = 2.0        # 滯留時間 (min)
n_reactors = 3   # 反應器數量

# 初始化濃度陣列
C = np.zeros(n_reactors + 1)
C[0] = C_in

# 計算每個反應器的出口濃度
for i in range(n_reactors):
    C[i+1] = C[i] / (1 + k * tau)

# 計算總轉化率
conversion = (C[0] - C[-1]) / C[0] * 100

print("CSTR 串聯質量平衡計算")
print("=" * 50)
print(f"進料濃度: {C[0]:.2f} mol/L")
for i in range(n_reactors):
    print(f"反應器 {i+1} 出口濃度: {C[i+1]:.2f} mol/L")
print(f"\n總轉化率: {conversion:.2f}%")

CSTR 串聯質量平衡計算
進料濃度: 10.00 mol/L
反應器 1 出口濃度: 5.00 mol/L
反應器 2 出口濃度: 2.50 mol/L
反應器 3 出口濃度: 1.25 mol/L

總轉化率: 87.50%


---
## 10. 效能優化技巧

### 10.1 向量化 vs 迴圈

In [149]:
# 效能比較：向量化 vs 明確迴圈
n = 1000000
arr = np.arange(n)

# 使用迴圈（慢）
start = time.time()
result_loop = []
for x in arr:
    result_loop.append(x ** 2)
time_loop = time.time() - start
print(f"\n明確迴圈時間: {time_loop:.4f} 秒")


明確迴圈時間: 0.2074 秒


In [150]:
# 使用向量化（快）
start = time.time()
result_vectorized = arr ** 2
time_vectorized = time.time() - start
print(f"向量化運算時間: {time_vectorized:.6f} 秒")

向量化運算時間: 0.002513 秒


In [153]:
print("效能比較：計算平方")
print("=" * 50)
print(f"資料量: {n:,} 個元素")
print(f"\n加速比: {time_loop / time_vectorized:.1f}x")
print(f"\n結論: 向量化運算比明確迴圈快 {time_loop / time_vectorized:.0f} 倍！")

效能比較：計算平方
資料量: 1,000,000 個元素

加速比: 82.5x

結論: 向量化運算比明確迴圈快 83 倍！


### 10.2 記憶體管理：View vs Copy

In [154]:
# 使用 view 而非 copy 節省記憶體
arr = np.arange(1000000)

# 創建 view（不複製數據）
arr_view = arr[::2]  # 取偶數索引

# 創建 copy（複製數據）
arr_copy = arr[::2].copy()

# 檢查是否共享記憶體
print(f"View 共享記憶體: {np.shares_memory(arr, arr_view)}")
print(f"Copy 共享記憶體: {np.shares_memory(arr, arr_copy)}")

# 注意：修改 view 會影響原陣列
print(f"\n原陣列第一個元素: {arr[0]}")
arr_view[0] = -999
print(f"修改 view 後，原陣列第一個元素: {arr[0]}")  # -999

View 共享記憶體: True
Copy 共享記憶體: False

原陣列第一個元素: 0
修改 view 後，原陣列第一個元素: -999


### 10.3 選擇適當的資料型態

In [155]:
# 預設 dtype 通常是 float64 或 int64
arr_default = np.array([1, 2, 3])
print(f"預設型態: {arr_default.dtype}")  # int64 (8 bytes)

# 如果數值範圍較小，可以使用較小的型態節省記憶體
arr_small = np.array([1, 2, 3], dtype=np.int8)  # 1 byte
print(f"int8 記憶體使用: {arr_small.nbytes} bytes")

# 化工應用：感測器數據通常不需要 float64 精度
sensor_data = np.random.randn(10000).astype(np.float32)
print(f"\nFloat32 記憶體: {sensor_data.nbytes / 1024:.2f} KB")

sensor_data_64 = sensor_data.astype(np.float64)
print(f"Float64 記憶體: {sensor_data_64.nbytes / 1024:.2f} KB")
print(f"記憶體節省: {(1 - sensor_data.nbytes / sensor_data_64.nbytes) * 100:.1f}%")

預設型態: int32
int8 記憶體使用: 3 bytes

Float32 記憶體: 39.06 KB
Float64 記憶體: 78.12 KB
記憶體節省: 50.0%


---
## 11. 常見錯誤與除錯

### 11.1 形狀不匹配錯誤

In [156]:
# 錯誤範例
try:
    A = np.array([[1, 2, 3]])  # shape: (1, 3)
    B = np.array([[1], [2]])   # shape: (2, 1)
    result = A + B
except ValueError as e:
    print(f"錯誤: {e}")

# 正確做法：確保形狀相容
A = np.array([[1, 2, 3]])  # (1, 3)
B = np.array([[1], [2], [3]])  # (3, 1)
result = A + B  # 廣播為 (3, 3)
print("\n正確的廣播結果:")
print(result)


正確的廣播結果:
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 11.2 整數除法陷阱

In [157]:
# Python 3 中已解決，但仍需注意 NumPy 行為
arr_int = np.array([1, 2, 3], dtype=int)

# 整數陣列除法會自動轉為 float
result_int = arr_int / 2
print(f"整數陣列除法: {result_int}")  # [0.5 1.  1.5]
print(f"資料型態: {result_int.dtype}")

# 確保使用浮點數運算
arr_float = arr_int.astype(float)
result_float = arr_float / 2
print(f"\n浮點數陣列除法: {result_float}")

整數陣列除法: [0.5 1.  1.5]
資料型態: float64

浮點數陣列除法: [0.5 1.  1.5]


### 11.3 複製 vs 視圖

In [158]:
# 陷阱：意外修改原陣列
original = np.array([1, 2, 3, 4, 5])
subset = original[1:4]  # 這是 view，不是 copy

print(f"原始陣列: {original}")
print(f"子集陣列: {subset}")

subset[0] = 999
print(f"\n修改 subset 後:")
print(f"原始陣列: {original}")  # [1 999 3 4 5]（原陣列被修改！）
print(f"子集陣列: {subset}")

# 安全做法：明確複製
original = np.array([1, 2, 3, 4, 5])
subset = original[1:4].copy()

subset[0] = 999
print(f"\n使用 copy() 後:")
print(f"原始陣列: {original}")  # [1 2 3 4 5]（原陣列未變）
print(f"子集陣列: {subset}")

原始陣列: [1 2 3 4 5]
子集陣列: [2 3 4]

修改 subset 後:
原始陣列: [  1 999   3   4   5]
子集陣列: [999   3   4]

使用 copy() 後:
原始陣列: [1 2 3 4 5]
子集陣列: [999   3   4]


---
## 12. 總結

### 核心概念回顧

本 Notebook 介紹了 NumPy 的核心概念與應用：

1. **陣列基礎**
   - NumPy 陣列的特性：同質性、高效能、固定大小
   - 建立陣列：從 list、內建函式、隨機數生成
   - 陣列屬性：ndim, shape, size, dtype

2. **陣列操作**
   - 索引與切片：一維、二維、布林索引、花式索引
   - 變形與組合：reshape, transpose, stack, split
   - 向量化運算：元素層級運算、數學函式

3. **統計分析**
   - 基本統計量：mean, std, var, max, min
   - 多維統計：axis 參數的使用
   - 百分位數與分位數

4. **線性代數**
   - 矩陣運算：轉置、行列式、反矩陣
   - 特徵值與特徵向量
   - 解線性方程組

5. **進階技巧**
   - 廣播機制：不同形狀陣列的運算
   - 效能優化：向量化、記憶體管理、資料型態選擇
   - 化工應用：反應動力學、物料平衡、製程控制

### 關鍵要點

- ✓ 優先使用向量化運算，避免明確迴圈
- ✓ 善用廣播機制處理不同形狀的陣列
- ✓ 理解 view 與 copy 的差異
- ✓ 選擇適當的資料型態節省記憶體
- ✓ 熟悉 axis 參數在多維陣列統計中的應用

### 下一步學習

完成本單元後，建議繼續學習：
- **Pandas**：建立在 NumPy 之上的資料處理套件
- **Matplotlib**：資料視覺化
- **SciPy**：科學計算與工程應用
- **Scikit-learn**：機器學習（大量使用 NumPy 陣列）

**恭喜您完成 Unit03 NumPy 數值計算基礎！**